### ISSUE TITLE
eyaml edit: undefined method `plain_text' on save

### ISSUE THREAD

**Issue by igalic** [sihil/hiera-eyaml-gpg#17]
I have a file foo.eyaml, that, unencrypted, looks like so:

``` yaml

---
postgresql::dbs:
  dbx:
    user: u1
    password: DEC(1)::GPG[Defect9advert-great]!
```

now I'd like to duplicate this, and have something like:

``` yaml

---
postgresql::dbs:
  dbx:
    user: u1
    password: DEC(1)::GPG[Defect9advert-great]!
  dby:
    user: u2
    password: DEC(2)::GPG[madrid_riot-Knot]!
```

when saving & closing the editor, I'm getting the following error:

```
[hiera-eyaml-core] !!! undefined method `plain_text' for #<Hiera::Backend::Eyaml::Parser::NonMatchToken:0x007f630b9c2938>
[hiera-eyaml-core] ["/home/igalic/.gem/ruby/2.1.2/gems/hiera-eyaml-2.0.3/lib/hiera/backend/eyaml/subcommands/edit.rb:69:in `block in execute'", "/home/igalic/.gem/ruby/2.1.2/gems/hiera-eyaml-2.0.3/lib/hiera/backend/eyaml/subcommands/edit.rb:66:in `map'", "/home/igalic/.gem/ruby/2.1.2/gems/hiera-eyaml-2.0.3/lib/hiera/backend/eyaml/subcommands/edit.rb:66:in `execute'", "/home/igalic/.gem/ruby/2.1.2/gems/hiera-eyaml-2.0.3/lib/hiera/backend/eyaml/CLI.rb:45:in `execute'", "/home/igalic/.gem/ruby/2.1.2/gems/hiera-eyaml-2.0.3/bin/eyaml:13:in `<top (required)>'", "/home/igalic/.gem/ruby/2.1.2/bin/eyaml:23:in `load'", "/home/igalic/.gem/ruby/2.1.2/bin/eyaml:23:in `<main>'"]
```
